name: apply workflow

on:
  workflow_call:
    inputs:
       environment:
        required: true
        type: string
jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./layers
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Terraform Plan Staging
        id: plan
        env:
          ENVIRONMENT_NAME: staging
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          ../scripts/plan.sh
        #if: github.event_name == 'pull_request'

      - name: Terraform Apply Staging
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          ENVIRONMENT_NAME: staging
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          ../scripts/apply.sh

